services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: SkillIntern
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: zhandos04
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://sducanteen_db:5432/SkillIntern
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: zhandos04

volumes:
  db-data: